### ISSUE TITLE
No longer can set className props

### ISSUE THREAD

**Issue by idmontie** [cuzzo/react-bem#3]
It appears that you can no longer write to the `child.props.className` in the latest version of React. Is there a workaround we can implement into this project, or is this method of autogenerating class names dead?

**Comment by idmontie** [comment]
The way I've seen other modules work around this is by modifying the props and then applying them to a clone of the element, see https://github.com/unicorn-standard/react-pacomo/blob/master/src/pacomo.js

**Comment by cuzzo** [comment]
Hey @idmontie,

I've been meaning to update react-bem to work similarly to react-pacomo for a few months, so it's definitely possible. I just haven't gotten around to it yet /=

Pull requests are definitely welcome [=

Cheers,

**Comment by idmontie** [comment]
Alright, I opened up a pull request. I haven't updated any tests for it yet (the tests time out on my machine). Let's do some code review on the PR.

**Comment by cuzzo** [comment]
Hey @idmontie,

At first glance, there's a few issues. The version of React in `package.json` wasn't updated, so it's hard to tell if it would work with the most recent version of React, but I'm pretty sure it won't work with the version of React in the `package.json`.

Also, this repo is written in es5, so a lot of the es6 features like `let`, `const`, `of`, `=>` and string interpolation won't work.

Finally, the `transform` method was removed--which is the public interface for the `BEMTransformer` that `ReactBEM` calls in it's `render` method. Because of that, all of the tests fail.

It looks like it's on the right track, though.

To get the tests running, you should only need to run:

``` bash
npm install
grunt test
```

If you can send me the errors your getting if that doesn't work, that would be helpful.

Thanks!

**Comment by idmontie** [comment]
Alright, on my local, I've got the tests running, but what is interesting is that the tests are failing because React changed its interface. 

For example, the bem_exists method in react-bem.test.js is throwing an exception because `el.type` is `undefined`.

`findRenderedDOMComponentWithClass` should return a ReactComponent ([as specified in its docs](https://facebook.github.io/react/docs/test-utils.html#findrendereddomcomponentwithclass)), but it is returning the DOM node instead, which means you can't get it's type.

A DOM node however has a "private" member named "_reactInternalComponent" which has a "_type", but that looks like something that can change in the future.
